version: '3.8'

networks:
  api:
    ipam:
      config:
        - subnet: 172.22.0.0/24

services:
  dev-db:
    build: .
    image: passtracker-dev
    networks:
      api:
        ipv4_address: 172.22.0.22
    ports:
      - "5432:5432"
