version: '3.8'

networks:
  net:
    ipam:
      config:
        - subnet: 172.22.0.0/24

services:
  dummy-data:
    build: ./dummy_data
    volumes:
      - ./dummy_data:/app

  dev-db:
    build: .
    image: passtracker-dev
    mem_limit: 512mb
    depends_on:
      dummy-data:
        condition: service_completed_successfully
    networks:
      net:
        ipv4_address: 172.22.0.22
    volumes:
      - ./dummy_data:/app
